import Head from 'next/head';
import Navbar from '../components/Navbar';
import HeroSection from '../components/home/HeroSection';
import ProfilesSection from '../components/home/ProfileSection';
import ProjectsSection from '../components/home/ProjectsSection';
import Footer from '../components/Footer';
import styles from '../styles/home/Index.module.css';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | Team Rocket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <HeroSection />
        <ProfilesSection />
        <ProjectsSection />

        <footer>
          <Footer />
        </footer>      
      </main>
    </div>
  );
}
