import Head from 'next/head';
import Navbar from '../components/Navbar';
import MotionDetector from '../components/projects/MotionDetector';
import OurProjects from '../components/projects/OurProjects';
import VisitRepo from '../components/projects/VisitRepo';
import Footer from '../components/Footer';
import styles from '../styles/projects/Projects.module.css';


export default function Projects() {
  return (
    <div>
      <Head>
        <title>Projects | Team Rocket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rocketmind.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <MotionDetector />
        <OurProjects />
        <VisitRepo />
        <footer>
          <Footer />
        </footer>      
      </main>
    </div>
  );
}
